version: '3.8'

services:
  backend_app:
    container_name: backend_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
